/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnalyticsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClickTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "TrackDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UrlTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}